[2020-07-14 00:08:42,375] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: news_fetch.download 2020-07-11T02:21:00+00:00 [queued]>
[2020-07-14 00:08:42,384] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: news_fetch.download 2020-07-11T02:21:00+00:00 [queued]>
[2020-07-14 00:08:42,384] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-14 00:08:42,384] {taskinstance.py:880} INFO - Starting attempt 3 of 4
[2020-07-14 00:08:42,384] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-14 00:08:42,691] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): download> on 2020-07-11T02:21:00+00:00
[2020-07-14 00:08:42,694] {standard_task_runner.py:53} INFO - Started process 3564 to run task
[2020-07-14 00:08:42,740] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: news_fetch.download 2020-07-11T02:21:00+00:00 [running]> tony-ThinkPad-X1-Carbon-7th
[2020-07-14 00:08:42,797] {taskinstance.py:1145} ERROR - Parameter validation failed:
Invalid bucket name "input-vid/images/result.jpg": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
Traceback (most recent call last):
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "airflow_home//dags/s3_push.py", line 44, in download_file
    response = s3_client.download_file(file_name,bucket,object_name)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/download.py", line 343, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 654, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 686, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/handlers.py", line 205, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "input-vid/images/result.jpg": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2020-07-14 00:08:42,800] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-14 00:08:52,368] {logging_mixin.py:112} INFO - [2020-07-14 00:08:52,368] {local_task_job.py:103} INFO - Task exited with return code 1
